### ISSUE TITLE
(uber ticket) Add bulk action for checksum report for list of druids

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1145]
#### Use case:  

"I have stuff stored in SDR;  I want to delete my local copies.  I want to be sure that’s ok."  This is about managing local storage -- want to make space;  want a better sense of “yup, you can delete this safely, your files are properly preserved”.

#### Ben's orig ticket:

Moving forward, we want to be able to run the preservation-core content verification report from Argo.

This script (https://github.com/sul-dlss/sdr-services-app/blob/master/bin/objectFileInfor.rb) currently produces the information needed for content owners to verify that their content has been successfully ingested into the preservation core.

This report should be available to users from Argo.

Implementation details are up to the Infrastructure team.

@vivnwong - tagging you for your awareness.

### Actionable Tickets:
- [ ] sul-dlss/preservation_catalog/issues/1202 - API endpoint for checksum reports
- [ ] #1530 - back end activejob implementation for checksum report
- [ ] #1534 - UI hookup for bulk action checksum report

**Comment by blalbrit** [comment]
@hannahfrost - wanted to tag you as well for tracking purposes.

**Comment by ndushay** [comment]
note: bulk action, async, please.

**Comment by andrewjbtw** [comment]
I've looked into this and the current script seems to be here: https://github.com/sul-dlss/sdr-services-app/blob/master/bin/objectFileInfor.rb But I have not checked if the version in the github repo matches the version on the server at the path listed in the comments in that script.

Current procedure appears to be:

1. User accessions objects
2. User requests MD5 report via SDRO ticket with list of druids
3. Ops logs into appropriate server
4. Ops creates a file with a list of druids (one druid per line) at /path/to/druid/file
5. Ops runs 
```bash
ruby objectFileInfor.rb /path/to/druid/file > /path/to/druid/file.csv
```
6. Ops attaches that CSV file to the ticket
7. User follows their own procedure to compare the checksums
8. If checksums match, user deletes their local copies

Example of completed ticket:
https://jirasul.stanford.edu/jira/projects/SDRGET/issues/SDRGET-2288

Notes:
- Even though this often gets referred to as an "md5 report", the CSV produced includes md5, sha1, and sha256. We should continue to report the same set of values.
- It does not look like an audit is run, given how quickly the script produces the CSV

**Comment by andrewjbtw** [comment]
For the bulk action:

- Input: pasting in a druid list seems sufficient but I don't know how users are generating their lists before filing their tickets
- Output: Downloadable CSV from Argo after the bulk action has been run

**Comment by oceanofsound** [comment]
In my case, I copy and paste the folder names directly from the Finder into the JIRA ticket (I have our staging volumes mounted on my desktop using SSHFS which makes the process pretty easy). Alternatively I could find the given set of objects in Argo and download a report, but the copy/paste option is quicker.

**Comment by ndushay** [comment]
(to be discussed at storytime 2019-08-26

approach 1:
- [ ] add API endpoint to prescat to provide checksum info for a druid
- [ ] allow argo to make ReST calls to prescat
- [ ] argo activejob loops through list of druids and assembles report with checksum info for each druid

approach 2:
- [ ] ensure argo has access to preservation storage-roots
- [ ] adapt existing script to run on argo as activejob

**Comment by tallenaz** [comment]
My vote is for approach 1: from the ops POV, proliferating access to the preservation storage roots makes provisioning new storage roots more complicated, and arguably makes preservation less secure.

**Comment by jmartin-sul** [comment]
> My vote is for approach 1: from the ops POV, proliferating access to the preservation storage roots makes provisioning new storage roots more complicated, and arguably makes preservation less secure.

that's a compelling argument, IMO, and very much in line with our previous efforts to restrict access to preservation (e.g. by using dor-services-app to proxy version queries and content retrieval requests that are ultimately fulfilled by the older sdr-services-app).

if the checksum calculation is being done upon request from argo, that may actually need to be fulfilled by a background job in pres cat, because for large content files, it's likely not safe to assume that the checksum calculation can finish before the network request times out.  so that would indicate something like:
* add a route to prescat to trigger calculation of checksum info for a list of druids.
  * checksums for the list of druids are calculated in bulk by a prescat background job
  * argo provides some sort of callback URL along with the list of druids
  * pres cat queues the druid list for checksum calculation.  upon completion, it hits the callback URL argo originally provided, indicating to argo that the checksums are ready for retrieval.
    * so... that indicates that the checksum results should also be retrievable by ReST call, and the URL from which to do the retrieval is provided in the callback pres cat makes to argo?  my hunch is that a large checksum list might not always be sendable in the callback itself, but maybe with a `POST` that'd work fine?  not sure.

new routes, tables, and jobs:
* pres cat:
  * a route for kicking off the checksum computation.  input:
    * druid list
    * argo callback URL for the specific checksum request
  * a route for retrieving a specific set of checksum results (unless that's sent directly in the callback to argo)
  * a job to do the checksum calculation for a list of druids, and to hit the argo callback URL upon completion of the job
* argo:
  * whatever routes and views are needed in the argo UI to set this report going
  * whatever routes and views are needed in the argo UI to provide results to the user after completion
  * a callback URL that pres cat can hit when it's done building a report
  * a table with a list of checksum reports, whether the report is complete, and if complete, where the report file lives (i doubt we want to put the results directly in the database, but i could be convinced otherwise)

so actually, maybe argo doesn't even need a new background job?  maybe argo just needs to be able to:
* hit the pres cat route for triggering the report
* provide a route of its own for pres cat to indicate report completion, and URL for report download
  * upon request to that route, argo goes and retrieves the report, and makes it available to the (human) argo user


and with that, we get no further proliferation of storage mounts, no direct human interaction with pres cat, and a (hopefully) reliable way to run large reports over large files (which likely cannot complete within the duration of a network request).

based on the use case @andrewjbtw described, i'm guessing this will mostly be run on large media files, making the pres cat background job part of things all the more important.

**Comment by tallenaz** [comment]
In practice, the script has never taken long, if that has implications for an async approach. From a quick look at the script, it looks like it calls out to moab-versioning to pull pre-existing checksums from a manifest and doesn't calculate?

```
StorageServices.retrieve_file_group('content',druid)
storage_object_version.file_inventory('version')
FileInventory.read_xml_file(@version_pathname.join('manifests'), 'version')
```

**Comment by jmartin-sul** [comment]
ah!  well then, a lot of what i said above may be a non-issue, since that was all based on re-calculation of checksums.  if it's just reading the checksums that are already in the files, that can probably happen in the span of a network call, unless the druid list is really long.

in that case, i'd be ok with the background job being in argo, and i'd have no strong opinion on whether the pres cat route should take a single druid or a list of druids.  slight preference for the former, maybe, since it'd reduce the number of network calls... though, on the other hand, one network call for each druid would reduce the chance that any given call would time out.

apologies for not looking at the script first, and assuming that checksums were being recalculated.

**Comment by ndushay** [comment]
per storytime 2019-09-03, go with bulk action approach, even though only one report for however many druids

**Comment by ndushay** [comment]
PR #1603 closes this ticket.  w00t!
