### ISSUE TITLE
when available, upgrade preservation-client

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#1770]
once https://github.com/sul-dlss/preservation-client/pull/29 is merged and a new version has been cut:
- [x] update the preservation-client gem (PR #1771)
- [x] add an example token setting in settings.yml (PR #1771)
- [x] update the [`Preservation::Client.configure` call](https://github.com/sul-dlss/argo/blob/21048696955e0842a9db67d5455c7af14f79104d/config/initializers/preservation_client.rb#L4) to use the new setting (PR #1771)
- [x] mint real tokens on stage and prod pres cat servers, and add those token values as corresponding overrides in the stage and prod shared configs settings (PRs sul-dlss/shared_configs/pull/1176, sul-dlss/shared_configs/pull/1173)

**Comment by jmartin-sul** [comment]
see also https://github.com/sul-dlss/preservation_catalog/pull/1306 and https://github.com/sul-dlss/preservation_catalog/issues/1298
