### ISSUE TITLE
[UBER] Set new CDL option (controlled digital lending) in object rights

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#2200]
We will have a new rights block for the fall 2020 term known as CDL (Controlled Digital Lending).  This will be a new form of access rights which will provide temporary access to materials for classes during the term.  Enforcement of access will occur via the PURL page with work done by the Access team, but we need to provide an ability to set the new rights in arbitrary objects.

The end result needs to be:

- Add a new option to the available object rights drop-down menu called "CDL".  This menu is shown on the item detail page when the user clicks the "Set Rights" button the left side of the page.
- This new option also needs to be available on the Bulk Actions page for the "Set object rights" action.
- When selected, this new option needs to be accepted as a valid choice and needs to be passed through the dor-services-app

Changes:
- [x]  ~~Update dor-services gem needs to recognize this new option and set the rights in the rightsMetadata datastream appropriately.  Ticket: sul-dlss/dor-services#712, PR: sul-dlss/dor-services#713~~
- [x] ~~Update rightsMetadata description in consul: https://consul.stanford.edu/display/chimera/Rights+metadata+--+the+rightsMetadata+datastream~~
- [x] ~~Update cocina models as needed  PR 1: sul-dlss/cocina-models#136~~
- [x] ~~File level access for cocina: https://github.com/sul-dlss/dor-rights-auth/pull/47#discussion_r476017934 and now a ticket: sul-dlss/cocina-models#140~~
- [x] ~~Update dor-rights-auth to recognize new cdl option in rights metadata.  Coordinate with Access team as needed, since they consume this gem too (see #cdl channel for communication about this).  Ticket: sul-dlss/dor-rights-auth#44, in progress PR: sul-dlss/dor-rights-auth#45~~
- [x] ~~Cut new release of dor-rights-auth gem, then bump it's version in dor-services gem and cut a new release of dor-services gem that uses it~~
- [x] ~~Update dor-services-app to map the new CDL option for the to  and from fedora classes.  Will need to bump to newer version of dor-rigthts-auth to get to the mapping to/from fedora working correctly.  Ticket: sul-dlss/dor-services-app#969, In progress PR: sul-dlss/dor-services-app#974~~
- [x] ~~Ensure indexing in argo shows the facet correctly for the new rights option.  This means dor_indexing_app need to be updated, possibly just requires bumping dor-indexing-app to use the new dor-rights-auth  Ticket: sul-dlss/dor_indexing_app#431~~
- [x] update sdr-api https://github.com/sul-dlss/sdr-api/pull/222
- [ ] This bug was exposed by CDL changes (need to support multiple collections in cocina models PR): https://github.com/sul-dlss/argo/issues/2233, PRs: https://github.com/sul-dlss/dor-services-app/pull/1027
- [x] Update Argo to use the updated version of dor-services gem (9.6.0 or better) and any newer gems updated above potentially (e.g. dor-rights-auth). In progress and almost complete PR: #2208

To test, deploy dor-services-app and argo to stage and verify that rights are being changed correctly in the cocina model and rightsMetadata stream.

The rights are defined as below:

```
<access type="read">
  <machine>
    <cdl>
	  <group rule="no-download">stanford</group>
    </cdl>
  </machine>
</access>
```

A full notes document with other analysis is here: https://docs.google.com/document/d/14JPhnBefJWcKZ0uFePZ1yn555aZwBoBigrE9-bsLbmg   (note we selected option A for the rights format)

Note: some fixtures in stage are here: https://argo-stage.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=cdl+fixtures

```
druid:gx705mr6900
druid:jw526hg2238
druid:kk311rb6988
druid:nz655fw7739
```

**Comment by justinlittman** [comment]
Can we not call this _cdl_, but rather _controlled digital lending_? It doesn't seem necessary to introduce another confusing acronym into the system.

**Comment by peetucket** [comment]
@cbeer, thoughts on what justin noted above (also noting that "CDL" often refers to the California Digital Library)

**Comment by peetucket** [comment]
actually - taken to the #cdl slack channel for broader discussion

**Comment by peetucket** [comment]
Just noting that argo pulls the rights metadata options from dor-services gem, so its possible the only change to Argo will be to bump the gem versions after changes are made elsewhere.

Argo constant for rights options: 

https://github.com/sul-dlss/argo/blob/master/lib/constants.rb#L6-L12

And where they come from in dor-services:

https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/rights_metadata_ds.rb#L62-L75

**Comment by jcoyne** [comment]
we need to figure out how this maps to and from the Cocina data model before proceeding. A good portion of our system is now only using Cocina and a failing to have a mapping could result in data loss.

**Comment by jcoyne** [comment]
It appears that we are adding file level access now? https://github.com/sul-dlss/dor-rights-auth/pull/47

**Comment by mejackreed** [comment]
FWIW, file level determination was added in sul-dlss/dor-rights-auth#47 for the following reasons:
 - we need a way to determine if a file has cdl rights
 - added to be consistent with how other rights things work

Happy to rethink/reimagine how this works, however we need an api to `cdl_rights_for_file?(filename)`
