### ISSUE TITLE
EPIC: Reset Stage and QA environment data

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3947]
**Why reset the testing environments?**

The stage environment has been running continuously since 2019. The QA environment has also been running for over a year. Both have accumulated a lot of data. Both have accumulated a lot of bad data. Bad data in the testing environments is a tax on all current and future development and the tax grows every week.

We need the stage and QA environments to reasonably approximate production so that:

- We can expect changes that pass tests on stage to work as expected in prod 
- We can identify bugs in a safe environment for testing without having to use prod objects

Some problem data is inevitable in testing environments because that's a part of testing. Either we create problem data to test the system or the function we are testing creates problem data. When the volume of problem data is small, it can either be remediated or ignored and it's not a drag on the rest of the system.

The problem with our current environments is that the volume of bad data is not small, and the cost of remediating it is also not small. Problem data

- can generate HB errors simply by existing (as can happen when indexing, validation, or audit finds it)
- can interfere with deployment
- can interfere with analysis
- can interfere with testing (automated and manual)
- makes our error reporting dashboards nearly unusable because it's difficult to tell what's a current issue and what is old
- can lead to extra time spent investigating problems that turn out not to matter because the test data is irrelevant to current concerns

The development team, product owners, the repository manager, and anyone else who uses stage for testing sees the cost of bad data on a regular basis. For the development team and the repository manager, it's become a constant, ongoing cost every week.

We are also running out of space in the stage "preservation" storage and should not keep expanding it. SDR has no simple way to delete data on a case by case basis without generating more errors.

Since stage is not actually a preservation system, we should be able to clear everything out and start over.

**Benefits of starting over**

- It will run faster and cleaner, at least at the start and for quite some time afterwards
- We can be more confident that issues we see are new and current
- We can be confident that all test data originates in Cocina. We migrated stage and QA when we migrated prod but prod got dedicated data remediation that the test environments did not. New data will ensure that there are no Fedora-origin problems left over. We left Fedora long enough ago that we don't need to keep migrated data for testing. New data should be fine.
- It will help us resolve a longstanding problem where the stage and QA environments share the same preservation storage mount and interfere with each other as a result. This is very hard to clean up in place. We could start over with separate mounts for separate environments.

**What do we need to start over?**

The SDR environment has to be seeded with certain objects to get started. (See https://github.com/sul-dlss/argo/issues/1782 for earlier discussion, but that was when SDR was based on Fedora.) We would need to make a full list but in terms of data we at the least need:

- The Internal System Objects APO
- Integration tests APO
- Any other APOs needed for specialized workflows and accessioning paths: ETD, GIS, WAS, Goobi
- SDR Graveyard APO for decommissions
- At least one agreement
- ??? 

It would also be nice to have the [Canonical objects](https://argo-stage.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=Canonical+objects) because they took much effort to create and they represent different types of objects for use in testing Purl and sul-embed behavior. 

With the foundational objects in place, we can create other test data as needed. There will be a judgement call on how far to go beyond the absolute minimum necessary to have a functional testing environment.

**Nice to have**

It would be nice to make this a repeatable process but not strictly necessary.

**Comment by andrewjbtw** [comment]
This will also require some coordination with stage users, especially Amy and Peter Chan because they actively use or create test objects there.

**Comment by mjgiarlo** [comment]
# Analysis

- [ ] For each application, document what needs resetting and how to reset it (keep in mind: databases, filesystems, other stores, e.g., Redis)
- [ ] Document the order in which applications should be reset (consider [this related ordered list](https://github.com/sul-dlss/DevOpsDocs/blob/master/infrastructure-shutdown-restart-ordering.md) as a start)
- [ ] Get complete list of seed objects (APOs, agreements, canonical objects, etc.) for QA and stage

# Execution

- [ ] Finish analysis above
- [ ] Work with POs (Andrew, Amy, Cathy, Peter C.) to schedule the outage
- [ ] Run through entire process in QA (to test it before running in stage)
- [ ] Run through entire process in stage

**Comment by mjgiarlo** [comment]
* argo
  * Solr collection: `argo_{qa,stage}`
  * Redis (used for sidekiq): `redis://argo-redis-{qa,stage}-01.stanford.edu:6379/`
  * Database: `argo` (MySQL) on `argo-db-{qa,stage}`
  * Directories: `/workflow/bulk/tmp/`, `/workflow/bulk/`
* common-accessioning
  * Redis: `redis://sul-robots-redis-{qa,stage}.stanford.edu:6379/`
  * Directories: `/dor/assembly/`, `/data/hydrus-files/`, `/dor/workspace`
* dor-services-app
* dor_indexing_app
* gis-robot-suite
* google-books
* happy-heron
* hydra_etd
* modsulator-app-rails
* pre-assembly
* preservation_catalog
* preservation_robots
* robot-console
* sdr-api
* sul_pub
* suri-rails
* technical-metadata-service
* was-pywb
* was-registrar-app
* was_robot_suite
* workflow-server-rails

**Comment by mjgiarlo** [comment]
# Execution

- [ ] Finish analysis above
- [ ] Work with POs (Andrew, Amy, Cathy, Peter C.) to schedule the outage
- [ ] Run through entire process in QA (to test it before running in stage)
- [ ] Run through entire process in stage

**Comment by mjgiarlo** [comment]
# Questions

* Should we reset Access portfolio components? If so, which ones? (Andrew)
* Should we clean up `/sdrpurl_transfer/` on DSA or not? (Andrew or Arcadia)
* Should we **not** clean up the 3M book records in gbooks stage? (Andrew)
* Should we retain any `Report` instances in ETD QA or stage envs? (Cathy)
  * We do not need to retain anything in the ETD app in QA or stage. (We do need the ETD APO and agreement in SDR in both envs.)
* Should we retain any logfiles in sul_pub QA or stage envs? (Peter M.)
* Does `sul_pub` use the `async` adapter for background jobs in QA and stage? (Peter M.)
* How much of the `sul_pub` database should be retained in QA and stage? (Peter M.)
* How much of the `/web-archiving-stacks` and `/was_unaccessioned_data` filesystems should be retained in QA and stage? (Laura, Ed, Peter C.)

**Comment by mjgiarlo** [comment]
# Export / Import Process

**TBD**

**Comment by mjgiarlo** [comment]
# Reset Process

NOTE: This is based on the restart ordering, and has some flaws. This is a draft only.

* Turn off Google Books processing (stage only)
* Quiet workers on robot-console and, once all busy processes have finished, stop all workers on robot-console
* For each of these apps, in the order specified here, export the data flagged for retention (per the [Export / Import Process](https://github.com/sul-dlss/argo/issues/3947#issuecomment-1553777114)), stop the application, and then clean up its [application state](https://github.com/sul-dlss/argo/issues/3947#issuecomment-1552224575):
  * common-accessioning
  * preservation_robots
  * was_robot_suite
  * gis-robot-suite
  * robot-console (at which point sul-robots-redis may be flushed)
  * modsulator
  * argo
  * pre-assembly
  * google-books
  * was-registrar-app
  * was-pywb
  * H2
  * ETD
  * sul_pub
  * DIA
  * at this point the Solr collection can have all its index entries removed (we don't need or want to stop Solr!)
  * techmd
  * prescat
  * sdr-api
  * suri-rails
  * workflow-server-rails
  * DSA
* For each of these apps, in the order specified here, start the application and import [application state](https://github.com/sul-dlss/argo/issues/3947#issuecomment-1552224575) flagged for retention (per the [Export / Import Process](https://github.com/sul-dlss/argo/issues/3947#issuecomment-1553777114))
  * DSA
  * (Solr should still be up and running and the collections we need should still be there.)
  * DIA
  * workflow-server-rails
  * suri-rails
  * sdr-api
  * prescat
  * techmd
  * sul_pub
  * ETD
  * H2
  * was-pywb
  * was-registrar-app
  * pre-assembly
  * google-books
  * argo
  * modsulator
  * robot-console (sul-robots-redis should still be up and ready to be used)
  * common-accessioning
  * preservation_robots
  * was_robot_suite
  * gis-robot-suite
* Ensure expected workers on robot-console
* Turn on Google Books processing (stage only)

**Comment by mjgiarlo** [comment]
Much of the above has been superseded by https://docs.google.com/document/d/1u1D3cFKfvhzaI6a1t7-VQTtbS27fmTXTqtfj7Esr7Rk/edit?pli=1

**Comment by andrewjbtw** [comment]
We did this in the workcycle that ended on October 13, 2023.
