### ISSUE TITLE
Fields to add/modify in Argo reports view

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4077]
There have been a number of requests to add fields to the Argo reports view over the past few years, only some of which have already been ticketed. This ticket is meant to put them all in one place:

- [x] "Release to" status (SW, EW, not released) #1011 
- [x] Access rights (view, download, location) #1055 
- [x] Embargo release date (if embargoed) #2589 
- [x] Number of constituents in a virtual object #3830 
- [x] Separate version and status into their own columns (currently combined: "v1 Accessioned")
- [x] Error message (currently the "Errors" field just reports a number)

More report fields may be added and/or this ticket might be split later.
