### ISSUE TITLE
Argo Folio Cutover checklist

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#4081]
Libsys will run their last (daily?) pickup of SDR purls to put in Symphony  MARC records on Fri 8/18 4:45am
The shared mount where the file(s) with the 856s get placed will remain available after that point.

## Before Symphony is Read only (Fri Aug 18, 5pm)
behind ils-cutover-in-progress feature flag, implement:
- [x] #4035 
- [x] #4079 
- [x] #4031 
- [x] #4032
    - [x] also ensure bulk action to refresh metadata from ILS will be called "Refresh MODS from Folio Instance HRID" after cutover

## After last release to SW functionality (Thurs Aug 17, 5pm?)
- [x] #4097 

## When Symphony becomes Read Only (After ? 5pm on Fri August 18 ?)
- [x] set  ils-change-in-progress feature flag to turn off functionality (in ??shared_configs??) 
- [x] ensure 5 tickets above have correctly disabled the stuff in Argo

## No updates to marc in ILS (Sat Aug 19 - ? Mon Aug 28 ?)
(nada)

## FOLIO Goes Live!  (? Mon, August 28 ?):
- [x] #4126
- [x] #4124
- [x] #4123

## After Confirmation that All is Working Appropriately with Folio
Partially written up as #4125

search on, case insensitive, e.g.:
    - [ ] `catalogRecordId`
    - [ ] `catalog_record_id`
    - [ ] `ckey`
    - [ ] `catkey`
    - [ ] `symphony`
    - [ ] `ils`
    - [ ] `folio`
    - [ ] ...
- [ ] remove code such as `if Settings.catalog_record_id == 'symphony'`  
- [ ] remove feature flag from settings, argo code and ??shared_configs??
- [ ] remove or alter app/services/catalog_record_id.rb
- [ ] `settings.yml` - what can be removed, should any defaults change

**Comment by ndushay** [comment]
all the known cleanup has been captured in #4125;  closing this.
