### ISSUE TITLE
Re-enable features beyond settings changes after Folio is ready - create PRs and mark 'em HOLD

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#4124]
This issue is to Create a PR(s) and **mark it HOLD** for turning features back on after Folio is ready.  **This issue is separate from changing the settings themselves, which is** #4123.  

There are a small number of Folio cutover changes that require more than simply changing the settings.  I haven't tracked exactly which changes these are ... I just know there are some, and one of them has to do with managed release, which had some UI code commented out.

The features we turned off, and that we may want Andrew to test before deploying to prod:
- [ ] accept registration form with or without catalogRecordId(s)
- [ ] allow creation of collection from catalogRecordId 
- [ ] turn on bulk action to refresh metadata from ILS
- [ ] allow metadata refresh on show page for an object (item, collection?)
- [ ] turn on release to SW functionality

Notes:
- for some disabled features, we commented out stuff (e.g. pulldown options) that would normally appear in the UI
- for some disabled features and/or specs, we added more than an if clause to facilitate disabling

For reference, essentially, these are the PRs that put in changes that may have to be changed for this ticket.
- [x] #4110 - addressed with settings flags
- [x] #4108 - some things were commented out to not appear in UI
- [x] #4100 - addressed with settings flags
- [x] #4091 - addressed with settings flags
- [x] #4088 - addressed with settings flags
- [x] search for `ils_cutover_in_progress` in case I missed something
- [x] search for `disable_release_prior_to_ils_cutover` in case I missed something
- [ ] search for "folio", "cutover" and ??? in case I missed something

**Comment by ndushay** [comment]
![image](https://github.com/sul-dlss/argo/assets/96775/b670c51f-2c16-44f3-a2ec-919d744e327d)
