### ISSUE TITLE
Argo Post Folio cutover cleanup

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#4125]
This issue is to create PR(s) for removing ILS cutover code.

Please do NOT do this in one giant PR. I recommend making multiple small PRs. This ticket can also be broken up into multiple tickets -- there is a lot here.

Notes:
- for some disabled features, we disabled tests
- for some disabled features, we had multiple PRs to achieve the end result desired.
- for some disabled features, we added more than an if clause to facilitate disabling
- for some disabled features, we commented out stuff (e.g. pulldown options) that would normally appear in the UI

Next:
- [ ] remove conditionals no longer needed for `ils_cutover_in_progress` and `disable_release_prior_to_ils_cutover`
- [ ] remove code such as `if Settings.catalog_record_id == 'symphony'`  
- [ ] remove or alter app/services/catalog_record_id.rb
- [ ] remove specs added specific to ils cutover (or convert 'em to regular specs) (see PR #4091) 
- [ ] remove specs added specific to ils cutover (or convert 'em to regular specs) (see PR #4088)
- [ ] remove specs added specific to ils cutover (or convert 'em to regular specs) (see PR #4083)
- [ ] remove settings from app code config  (see PR #4110 and PR #4100)
- [ ] `settings.yml` - what can be removed, should any defaults change
- [ ] any tests or other code to be cleaned up (see PR #4108)
- [ ] does the README need updating?
- [ ] in case I missed something, search on , case insensitive, e.g.:
    - [ ] `cutover` 
    - [ ] `catalogRecordId`
    - [ ] `catalog_record_id`
    - [ ] `ckey`
    - [ ] `catkey`
    - [ ] `symphony`
    - [ ] `ils`
    - [ ] `folio`
    - [ ] ...

After all the above is merged and deployed:
- [ ] remove the appropriate settings from shared_configs for qa, stage and prod.

**Comment by ndushay** [comment]
@andrewjbtw are there spots in Argo where we can stop displaying catkey, or should it keep showing as is for a while?

**Comment by mjgiarlo** [comment]
> @andrewjbtw are there spots in Argo where we can stop displaying catkey, or should it keep showing as is for a while?

@andrewjbtw We currently allow Argo's forms to silently pass along catkey-style catalog record IDs in Cocina. Is that still valuable or could it be excised?
